apiVersion: apps/v1
kind: Deployment
metadata:
  name: velocity
spec:
  replicas: 1
  template:
    metadata:
      annotations:
        vault.security.banzaicloud.io/vault-addr: https://vault.vault:8200
        vault.security.banzaicloud.io/vault-role: di-velocity
        vault.security.banzaicloud.io/vault-skip-verify: "true"
        prometheus.io/path: /metrics
        prometheus.io/port: "2112"
        prometheus.io/scrape: "true"
    spec:
      serviceAccountName: velocity
      containers:
      - image: jasonblanchard/di-velocity:latest
        name: velocity
        envFrom:
        - configMapRef:
            name: velocity-config
        # livenessProbe:
        #   exec:
        #     command:
        #     - grep
        #     - -q
        #     - UP
        #     - /usr/src/app/HEALTH_STATUS
        # readinessProbe:
        #   exec:
        #     command:
        #     - grep
        #     - -q
        #     - UP
        #     - /usr/src/app/HEALTH_STATUS
          # initialDelaySeconds: 5
          # periodSeconds: 5
        ports:
        - containerPort: 2112
          name: prometheus
          protocol: TCP
