apiVersion: v1
kind: Pod
metadata:
  name: velocity-psql-debugger
  namespace: di-production
  annotations:
    vault.security.banzaicloud.io/vault-addr: https://vault.vault:8200
    vault.security.banzaicloud.io/vault-role: di-velocity
    vault.security.banzaicloud.io/vault-skip-verify: "true"
spec:
  serviceAccountName: velocity
  containers:
  - name: psql
    image: postgres
    command:
      - /bin/bash
      - -c
      - |
        tail -f /dev/null
    env:
      - name: USER
        value: postgres
      - name: PGPASSWORD
        value: vault:secret/data/di-velocity/production/app#DB_PASSWORD
      - name: HOST
        value: di-velocity-psql
      - name: PORT
        value: "5432"
      - name: DATABASE
        value: di_velocity
