apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
bases:
  - ../base
nameSuffix: -production
commonLabels:
  environment: production
resources:
  - db.yaml
configMapGenerator:
- literals:
  - NATS_URL=nats://nats:4222
  - DB_USER=postgres
  - DB_NAME=di_velocity
  - DB_PASSWORD=vault:secret/data/di-velocity/production/app#DB_PASSWORD
  - DB_HOST=di-velocity-psql-production
  name: velocity-config
  behavior: merge
